version: "3.8"

services:
  server:
    build:
      context: server
      dockerfile: dev.Dockerfile
    container_name: wowclassic-bg-ocr-server-dev
    user: node
    working_dir: /usr/src
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - SAVE_PREPROCESSED=true
      - TZ=America/New_York
    volumes:
      - ./server:/usr/src
      - server_nm:/usr/src/node_modules

  client:
    image: lobsterbandit/dev-golang:edge
    container_name: wowclassic-bg-ocr-client-dev
    tty: true
    working_dir: /usr/src
    volumes:
      - .:/usr/src

volumes:
  server_nm:
