version: "3.8"

services:
  server:
    build:
      context: server
      dockerfile: dev.Dockerfile
    container_name: wowclassic-bg-ocr-server-dev
    user: node
    working_dir: /usr/src
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - SAVE_PREPROCESSED=true
    volumes:
      - ./server:/usr/src
      - server_nm:/usr/src/node_modules

volumes:
  server_nm:
