version: "3.8"

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: wowclassic-bg-ocr-server
    init: true
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - SAVE_PREPROCESSED=true
      - TZ=America/New_York
    volumes:
      # map this volume to save images from the express server
      # if SAVE_PREPROCESSED is set to true
      - ./server/testdata:/testdata
