version: "3.8"

services:
  tesseractjs:
    image: node:current-buster
    container_name: tesseractjs
    user: node
    tty: true
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
