version: "3.8"

services:
  server:
    build: server
    container_name: wowclassic-bg-ocr-server
    ports:
      - "3003:3003"
    environment:
      - SAVE_PREPROCESSED=true
      - NODE_ENV=production
      - PORT=3003
    volumes:
      # map this volume to save images from the express server
      # if SAVE_PREPROCESSED is set to true
      - ./server/testdata:/testdata
