version: "3.8"

services:
  server:
    build:
      context: server
      dockerfile: dev.Dockerfile
    container_name: bg-alert-classic-server-dev
    user: node
    working_dir: /usr/src
    ports:
      - "${PORT:-3003}:${PORT:-3003}"
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3003}
      - SAVE_PREPROCESSED=true
      - TZ=${TZ}
    volumes:
      - ./server:/usr/src
      - server_nm:/usr/src/node_modules

  client:
    image: lobsterbandit/dev-golang:edge
    container_name: bg-alert-classic-dev
    tty: true
    working_dir: /workspaces/bg-alert-classic
    environment:
      - TZ=${TZ}
    volumes:
      - .:/workspaces/bg-alert-classic

volumes:
  server_nm:
